"""create exceptions and rule runs

Revision ID: 1291b392a667
Revises: 4082239430dd
Create Date: 2026-10-07 23:51:57.740363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1291b392a667'
down_revision: Union[str, Sequence[str], None] = '4082239430dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_exceptions',
    sa.Column('source', sa.String(length=10), server_default='RULE', nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('rule_version', sa.Integer(), nullable=True),
    sa.Column('anomaly_model', sa.String(length=60), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('source_record_id', sa.Uuid(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedup_key', sa.String(length=200), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=12), server_default='NEW', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint("(source = 'RULE') = (rule_id IS NOT NULL)", name=op.f('ck_audit_exceptions_rule_link')),
    sa.CheckConstraint("severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name=op.f('ck_audit_exceptions_severity')),
    sa.CheckConstraint("source IN ('RULE', 'ANOMALY')", name=op.f('ck_audit_exceptions_source')),
    sa.CheckConstraint("status IN ('NEW', 'IN_CASE', 'SUPPRESSED')", name=op.f('ck_audit_exceptions_status')),
    sa.ForeignKeyConstraint(['rule_id'], ['audit.audit_rules.id'], name=op.f('fk_audit_exceptions_rule_id_audit_rules')),
    sa.ForeignKeyConstraint(['source_record_id'], ['audit.audit_source_records.id'], name=op.f('fk_audit_exceptions_source_record_id_audit_source_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_exceptions')),
    sa.UniqueConstraint('dedup_key', name=op.f('uq_audit_exceptions_dedup_key')),
    schema='audit'
    )
    op.create_index(op.f('ix_audit_exceptions_case_id'), 'audit_exceptions', ['case_id'], unique=False, schema='audit')
    op.create_index('ix_audit_exceptions_entity', 'audit_exceptions', ['entity_type', 'entity_id'], unique=False, schema='audit')
    op.create_index(op.f('ix_audit_exceptions_rule_id'), 'audit_exceptions', ['rule_id'], unique=False, schema='audit')
    op.create_index(op.f('ix_audit_exceptions_status'), 'audit_exceptions', ['status'], unique=False, schema='audit')
    op.create_index(op.f('ix_audit_exceptions_tenant_id'), 'audit_exceptions', ['tenant_id'], unique=False, schema='audit')
    op.create_table('audit_rule_runs',
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='RUNNING', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_checked', sa.Integer(), server_default='0', nullable=False),
    sa.Column('exceptions_created', sa.Integer(), server_default='0', nullable=False),
    sa.Column('duplicates_skipped', sa.Integer(), server_default='0', nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint("status IN ('RUNNING', 'SUCCEEDED', 'FAILED')", name=op.f('ck_audit_rule_runs_status')),
    sa.CheckConstraint("trigger_type IN ('EVENT', 'BATCH', 'MANUAL')", name=op.f('ck_audit_rule_runs_trigger_type')),
    sa.ForeignKeyConstraint(['rule_id'], ['audit.audit_rules.id'], name=op.f('fk_audit_rule_runs_rule_id_audit_rules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_rule_runs')),
    schema='audit'
    )
    op.create_index(op.f('ix_audit_rule_runs_rule_id'), 'audit_rule_runs', ['rule_id'], unique=False, schema='audit')
    op.create_index(op.f('ix_audit_rule_runs_tenant_id'), 'audit_rule_runs', ['tenant_id'], unique=False, schema='audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_rule_runs_tenant_id'), table_name='audit_rule_runs', schema='audit')
    op.drop_index(op.f('ix_audit_rule_runs_rule_id'), table_name='audit_rule_runs', schema='audit')
    op.drop_table('audit_rule_runs', schema='audit')
    op.drop_index(op.f('ix_audit_exceptions_tenant_id'), table_name='audit_exceptions', schema='audit')
    op.drop_index(op.f('ix_audit_exceptions_status'), table_name='audit_exceptions', schema='audit')
    op.drop_index(op.f('ix_audit_exceptions_rule_id'), table_name='audit_exceptions', schema='audit')
    op.drop_index('ix_audit_exceptions_entity', table_name='audit_exceptions', schema='audit')
    op.drop_index(op.f('ix_audit_exceptions_case_id'), table_name='audit_exceptions', schema='audit')
    op.drop_table('audit_exceptions', schema='audit')
    # ### end Alembic commands ###
