"""evidence

Revision ID: 2697b0c9dad0
Revises: 7014cac14696
Create Date: 2026-10-08 23:51:44.524972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2697b0c9dad0'
down_revision: Union[str, Sequence[str], None] = '7014cac14696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_evidence',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('evidence_type', sa.String(length=15), nullable=False),
    sa.Column('source_system', sa.String(length=15), nullable=False),
    sa.Column('source_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('captured_by', sa.Uuid(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('contains_phi', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='ACTIVE', nullable=False),
    sa.Column('superseded_reason', sa.Text(), nullable=True),
    sa.Column('superseded_by', sa.Uuid(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint("evidence_type IN ('DOCUMENT', 'TRANSACTION', 'EMAIL', 'APPROVAL', 'LOG', 'ATTACHMENT', 'CHECKLIST')", name=op.f('ck_audit_evidence_evidence_type')),
    sa.CheckConstraint("source_system IN ('procurement', 'insurance', 'erp', 'his', 'manual')", name=op.f('ck_audit_evidence_source_system')),
    sa.CheckConstraint("status IN ('ACTIVE', 'SUPERSEDED')", name=op.f('ck_audit_evidence_status')),
    sa.CheckConstraint('(document_id IS NULL) <> (snapshot IS NULL)', name=op.f('ck_audit_evidence_one_source')),
    sa.ForeignKeyConstraint(['document_id'], ['audit.documents.id'], name=op.f('fk_audit_evidence_document_id_documents')),
    sa.ForeignKeyConstraint(['superseded_by'], ['audit.audit_evidence.id'], name=op.f('fk_audit_evidence_superseded_by_audit_evidence')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_evidence')),
    schema='audit'
    )
    op.create_index(op.f('ix_audit_evidence_tenant_id'), 'audit_evidence', ['tenant_id'], unique=False, schema='audit')
    op.create_index('ix_audit_evidence_tenant_status', 'audit_evidence', ['tenant_id', 'status'], unique=False, schema='audit')
    op.create_table('audit_evidence_links',
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('linked_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint("target_type IN ('CASE', 'FINDING', 'ACTION')", name=op.f('ck_audit_evidence_links_target_type')),
    sa.ForeignKeyConstraint(['evidence_id'], ['audit.audit_evidence.id'], name=op.f('fk_audit_evidence_links_evidence_id_audit_evidence')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_evidence_links')),
    sa.UniqueConstraint('evidence_id', 'target_type', 'target_id', name=op.f('uq_audit_evidence_links_evidence_id_target_type_target_id')),
    schema='audit'
    )
    op.create_index(op.f('ix_audit_evidence_links_evidence_id'), 'audit_evidence_links', ['evidence_id'], unique=False, schema='audit')
    op.create_index('ix_audit_evidence_links_target', 'audit_evidence_links', ['tenant_id', 'target_type', 'target_id'], unique=False, schema='audit')
    op.create_index(op.f('ix_audit_evidence_links_tenant_id'), 'audit_evidence_links', ['tenant_id'], unique=False, schema='audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_evidence_links_tenant_id'), table_name='audit_evidence_links', schema='audit')
    op.drop_index('ix_audit_evidence_links_target', table_name='audit_evidence_links', schema='audit')
    op.drop_index(op.f('ix_audit_evidence_links_evidence_id'), table_name='audit_evidence_links', schema='audit')
    op.drop_table('audit_evidence_links', schema='audit')
    op.drop_index('ix_audit_evidence_tenant_status', table_name='audit_evidence', schema='audit')
    op.drop_index(op.f('ix_audit_evidence_tenant_id'), table_name='audit_evidence', schema='audit')
    op.drop_table('audit_evidence', schema='audit')
    # ### end Alembic commands ###
