"""create rule tables

Revision ID: 28a72430973c
Revises: 7bf818d29ef4
Create Date: 2026-10-07 11:40:53.411863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28a72430973c'
down_revision: Union[str, Sequence[str], None] = '7bf818d29ef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_config')),
    sa.UniqueConstraint('tenant_id', 'key', name=op.f('uq_audit_config_tenant_id')),
    schema='audit'
    )
    op.create_index(op.f('ix_audit_config_tenant_id'), 'audit_config', ['tenant_id'], unique=False, schema='audit')
    op.create_table('audit_rules',
    sa.Column('rule_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=30), nullable=False),
    sa.Column('department_scope', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='DRAFT', nullable=False),
    sa.Column('current_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint("domain IN ('PROCUREMENT', 'INSURANCE', 'BILLING', 'FINANCIAL', 'COMPLIANCE')", name=op.f('ck_audit_rules_domain')),
    sa.CheckConstraint("severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name=op.f('ck_audit_rules_severity')),
    sa.CheckConstraint("status IN ('DRAFT', 'ACTIVE', 'INACTIVE')", name=op.f('ck_audit_rules_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_rules')),
    sa.UniqueConstraint('tenant_id', 'rule_code', name=op.f('uq_audit_rules_tenant_id')),
    schema='audit'
    )
    op.create_index(op.f('ix_audit_rules_domain'), 'audit_rules', ['domain'], unique=False, schema='audit')
    op.create_index(op.f('ix_audit_rules_status'), 'audit_rules', ['status'], unique=False, schema='audit')
    op.create_index(op.f('ix_audit_rules_tenant_id'), 'audit_rules', ['tenant_id'], unique=False, schema='audit')
    op.create_table('audit_rule_versions',
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['audit.audit_rules.id'], name=op.f('fk_audit_rule_versions_rule_id_audit_rules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_rule_versions')),
    sa.UniqueConstraint('rule_id', 'version', name=op.f('uq_audit_rule_versions_rule_id')),
    schema='audit'
    )
    op.create_index(op.f('ix_audit_rule_versions_tenant_id'), 'audit_rule_versions', ['tenant_id'], unique=False, schema='audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_rule_versions_tenant_id'), table_name='audit_rule_versions', schema='audit')
    op.drop_table('audit_rule_versions', schema='audit')
    op.drop_index(op.f('ix_audit_rules_tenant_id'), table_name='audit_rules', schema='audit')
    op.drop_index(op.f('ix_audit_rules_status'), table_name='audit_rules', schema='audit')
    op.drop_index(op.f('ix_audit_rules_domain'), table_name='audit_rules', schema='audit')
    op.drop_table('audit_rules', schema='audit')
    op.drop_index(op.f('ix_audit_config_tenant_id'), table_name='audit_config', schema='audit')
    op.drop_table('audit_config', schema='audit')
    # ### end Alembic commands ###
