"""notifications

Revision ID: 3d3daa6aeea1
Revises: afe40d7ad046
Create Date: 2026-10-08 12:50:24.516683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3daa6aeea1'
down_revision: Union[str, Sequence[str], None] = 'afe40d7ad046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_role', sa.String(length=10), nullable=True),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(recipient_id IS NULL) <> (recipient_role IS NULL)', name=op.f('ck_notifications_one_recipient')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('seq', name=op.f('uq_notifications_seq')),
    schema='audit'
    )
    op.create_index('ix_notifications_role', 'notifications', ['tenant_id', 'recipient_role'], unique=False, schema='audit')
    op.create_index('ix_notifications_user', 'notifications', ['tenant_id', 'recipient_id'], unique=False, schema='audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_user', table_name='notifications', schema='audit')
    op.drop_index('ix_notifications_role', table_name='notifications', schema='audit')
    op.drop_table('notifications', schema='audit')
    # ### end Alembic commands ###
