"""findings

Revision ID: 60b07770452e
Revises: 094618fa4227
Create Date: 2026-10-09 00:02:40.503705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60b07770452e'
down_revision: Union[str, Sequence[str], None] = '094618fa4227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_findings',
    sa.Column('finding_number', sa.String(length=20), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('criteria', sa.Text(), nullable=True),
    sa.Column('cause', sa.Text(), nullable=True),
    sa.Column('effect', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('financial_impact', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('owner_department_id', sa.Uuid(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='DRAFT', nullable=False),
    sa.Column('management_response', sa.Text(), nullable=True),
    sa.Column('ai_drafted_fields', postgresql.ARRAY(sa.String(length=30)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('dismiss_reason', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('previous_finding_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint("risk_level IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name=op.f('ck_audit_findings_risk_level')),
    sa.CheckConstraint("status IN ('DRAFT', 'UNDER_REVIEW', 'CONFIRMED', 'DISMISSED', 'ACTION_ASSIGNED', 'RESOLVED', 'VERIFIED', 'REOPENED', 'CLOSED')", name=op.f('ck_audit_findings_status')),
    sa.ForeignKeyConstraint(['case_id'], ['audit.audit_cases.id'], name=op.f('fk_audit_findings_case_id_audit_cases')),
    sa.ForeignKeyConstraint(['previous_finding_id'], ['audit.audit_findings.id'], name=op.f('fk_audit_findings_previous_finding_id_audit_findings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_findings')),
    sa.UniqueConstraint('tenant_id', 'finding_number', name=op.f('uq_audit_findings_tenant_id_finding_number')),
    schema='audit'
    )
    op.create_index('ix_audit_findings_tenant_case', 'audit_findings', ['tenant_id', 'case_id'], unique=False, schema='audit')
    op.create_index('ix_audit_findings_tenant_due', 'audit_findings', ['tenant_id', 'due_date'], unique=False, schema='audit')
    op.create_index(op.f('ix_audit_findings_tenant_id'), 'audit_findings', ['tenant_id'], unique=False, schema='audit')
    op.create_index('ix_audit_findings_tenant_owner', 'audit_findings', ['tenant_id', 'owner_user_id'], unique=False, schema='audit')
    op.create_index('ix_audit_findings_tenant_status', 'audit_findings', ['tenant_id', 'status'], unique=False, schema='audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_findings_tenant_status', table_name='audit_findings', schema='audit')
    op.drop_index('ix_audit_findings_tenant_owner', table_name='audit_findings', schema='audit')
    op.drop_index(op.f('ix_audit_findings_tenant_id'), table_name='audit_findings', schema='audit')
    op.drop_index('ix_audit_findings_tenant_due', table_name='audit_findings', schema='audit')
    op.drop_index('ix_audit_findings_tenant_case', table_name='audit_findings', schema='audit')
    op.drop_table('audit_findings', schema='audit')
    # ### end Alembic commands ###
