"""create audit_processed_events

Revision ID: 7bf818d29ef4
Revises: bb3c15fc6a69
Create Date: 2026-10-04 23:39:56.866752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf818d29ef4'
down_revision: Union[str, Sequence[str], None] = 'bb3c15fc6a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_processed_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('source_record_id', sa.Uuid(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['source_record_id'], ['audit.audit_source_records.id'], name=op.f('fk_audit_processed_events_source_record_id_audit_source_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_processed_events')),
    sa.UniqueConstraint('event_id', name=op.f('uq_audit_processed_events_event_id')),
    schema='audit'
    )
    op.create_index(op.f('ix_audit_processed_events_tenant_id'), 'audit_processed_events', ['tenant_id'], unique=False, schema='audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_processed_events_tenant_id'), table_name='audit_processed_events', schema='audit')
    op.drop_table('audit_processed_events', schema='audit')
    # ### end Alembic commands ###
