"""corrective actions

Revision ID: 815da59fcc5b
Revises: 60b07770452e
Create Date: 2026-10-09 11:31:16.624309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '815da59fcc5b'
down_revision: Union[str, Sequence[str], None] = '60b07770452e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corrective_actions',
    sa.Column('action_number', sa.String(length=20), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('owner_department_id', sa.Uuid(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('required_evidence_type', sa.String(length=15), nullable=True),
    sa.Column('status', sa.String(length=12), server_default='OPEN', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_note', sa.Text(), nullable=True),
    sa.Column('return_note', sa.Text(), nullable=True),
    sa.Column('extension_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reminders_sent', postgresql.ARRAY(sa.String(length=20)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint("status IN ('OPEN', 'IN_PROGRESS', 'SUBMITTED', 'RETURNED', 'VERIFIED', 'CLOSED')", name=op.f('ck_corrective_actions_status')),
    sa.CheckConstraint('extension_count >= 0', name=op.f('ck_corrective_actions_extension_count')),
    sa.ForeignKeyConstraint(['case_id'], ['audit.audit_cases.id'], name=op.f('fk_corrective_actions_case_id_audit_cases')),
    sa.ForeignKeyConstraint(['finding_id'], ['audit.audit_findings.id'], name=op.f('fk_corrective_actions_finding_id_audit_findings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corrective_actions')),
    sa.UniqueConstraint('tenant_id', 'action_number', name=op.f('uq_corrective_actions_tenant_id_action_number')),
    schema='audit'
    )
    op.create_index('ix_corrective_actions_tenant_due', 'corrective_actions', ['tenant_id', 'due_date'], unique=False, schema='audit')
    op.create_index('ix_corrective_actions_tenant_finding', 'corrective_actions', ['tenant_id', 'finding_id'], unique=False, schema='audit')
    op.create_index(op.f('ix_corrective_actions_tenant_id'), 'corrective_actions', ['tenant_id'], unique=False, schema='audit')
    op.create_index('ix_corrective_actions_tenant_owner', 'corrective_actions', ['tenant_id', 'owner_user_id'], unique=False, schema='audit')
    op.create_index('ix_corrective_actions_tenant_status', 'corrective_actions', ['tenant_id', 'status'], unique=False, schema='audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_corrective_actions_tenant_status', table_name='corrective_actions', schema='audit')
    op.drop_index('ix_corrective_actions_tenant_owner', table_name='corrective_actions', schema='audit')
    op.drop_index(op.f('ix_corrective_actions_tenant_id'), table_name='corrective_actions', schema='audit')
    op.drop_index('ix_corrective_actions_tenant_finding', table_name='corrective_actions', schema='audit')
    op.drop_index('ix_corrective_actions_tenant_due', table_name='corrective_actions', schema='audit')
    op.drop_table('corrective_actions', schema='audit')
    # ### end Alembic commands ###
