"""create audit_source_records

Revision ID: bb3c15fc6a69
Revises: 
Create Date: 2026-10-04 23:17:02.826615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb3c15fc6a69'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_source_records',
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_source_records')),
    schema='audit'
    )
    op.create_index(op.f('ix_audit_source_records_tenant_id'), 'audit_source_records', ['tenant_id'], unique=False, schema='audit')
    op.create_index('ix_audit_source_records_trail', 'audit_source_records', ['source_system', 'entity_type', 'entity_id', 'captured_at'], unique=False, schema='audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_source_records_trail', table_name='audit_source_records', schema='audit')
    op.drop_index(op.f('ix_audit_source_records_tenant_id'), table_name='audit_source_records', schema='audit')
    op.drop_table('audit_source_records', schema='audit')
    # ### end Alembic commands ###
