"""audit cases

Revision ID: d7fb9f0ec989
Revises: 7a25e5dd2605
Create Date: 2026-10-08 12:05:28.939442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7fb9f0ec989'
down_revision: Union[str, Sequence[str], None] = '7a25e5dd2605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_case_counters',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_case_counters')),
    sa.UniqueConstraint('tenant_id', 'year', name=op.f('uq_audit_case_counters_tenant_id_year')),
    schema='audit'
    )
    op.create_index(op.f('ix_audit_case_counters_tenant_id'), 'audit_case_counters', ['tenant_id'], unique=False, schema='audit')
    op.create_table('audit_cases',
    sa.Column('case_number', sa.String(length=20), nullable=False),
    sa.Column('domain', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('primary_entity_type', sa.String(length=60), nullable=False),
    sa.Column('primary_entity_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='OPEN', nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('is_restricted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('closure_reason', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint("domain IN ('PROCUREMENT', 'INSURANCE', 'BILLING', 'FINANCIAL', 'COMPLIANCE')", name=op.f('ck_audit_cases_domain')),
    sa.CheckConstraint("priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name=op.f('ck_audit_cases_priority')),
    sa.CheckConstraint("source IN ('RULE', 'ANOMALY', 'MANUAL')", name=op.f('ck_audit_cases_source')),
    sa.CheckConstraint("status IN ('OPEN', 'ASSIGNED', 'IN_INVESTIGATION', 'ON_HOLD', 'PENDING_REVIEW', 'FINDING_CONFIRMED', 'NO_ISSUE', 'ACTION_IN_PROGRESS', 'CLOSED', 'REOPENED')", name=op.f('ck_audit_cases_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_cases')),
    sa.UniqueConstraint('tenant_id', 'case_number', name=op.f('uq_audit_cases_tenant_id_case_number')),
    schema='audit'
    )
    op.create_index('ix_audit_cases_tenant_assigned', 'audit_cases', ['tenant_id', 'assigned_to'], unique=False, schema='audit')
    op.create_index(op.f('ix_audit_cases_tenant_id'), 'audit_cases', ['tenant_id'], unique=False, schema='audit')
    op.create_index('ix_audit_cases_tenant_status', 'audit_cases', ['tenant_id', 'status'], unique=False, schema='audit')
    op.create_table('audit_case_comments',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('length(trim(body)) > 0', name=op.f('ck_audit_case_comments_body_not_empty')),
    sa.ForeignKeyConstraint(['case_id'], ['audit.audit_cases.id'], name=op.f('fk_audit_case_comments_case_id_audit_cases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_case_comments')),
    schema='audit'
    )
    op.create_index(op.f('ix_audit_case_comments_case_id'), 'audit_case_comments', ['case_id'], unique=False, schema='audit')
    op.create_index(op.f('ix_audit_case_comments_tenant_id'), 'audit_case_comments', ['tenant_id'], unique=False, schema='audit')
    op.create_table('audit_case_exceptions',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('exception_id', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['audit.audit_cases.id'], name=op.f('fk_audit_case_exceptions_case_id_audit_cases')),
    sa.ForeignKeyConstraint(['exception_id'], ['audit.audit_exceptions.id'], name=op.f('fk_audit_case_exceptions_exception_id_audit_exceptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_case_exceptions')),
    sa.UniqueConstraint('exception_id', name=op.f('uq_audit_case_exceptions_exception_id')),
    schema='audit'
    )
    op.create_index(op.f('ix_audit_case_exceptions_case_id'), 'audit_case_exceptions', ['case_id'], unique=False, schema='audit')
    op.create_index(op.f('ix_audit_case_exceptions_tenant_id'), 'audit_case_exceptions', ['tenant_id'], unique=False, schema='audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_case_exceptions_tenant_id'), table_name='audit_case_exceptions', schema='audit')
    op.drop_index(op.f('ix_audit_case_exceptions_case_id'), table_name='audit_case_exceptions', schema='audit')
    op.drop_table('audit_case_exceptions', schema='audit')
    op.drop_index(op.f('ix_audit_case_comments_tenant_id'), table_name='audit_case_comments', schema='audit')
    op.drop_index(op.f('ix_audit_case_comments_case_id'), table_name='audit_case_comments', schema='audit')
    op.drop_table('audit_case_comments', schema='audit')
    op.drop_index('ix_audit_cases_tenant_status', table_name='audit_cases', schema='audit')
    op.drop_index(op.f('ix_audit_cases_tenant_id'), table_name='audit_cases', schema='audit')
    op.drop_index('ix_audit_cases_tenant_assigned', table_name='audit_cases', schema='audit')
    op.drop_table('audit_cases', schema='audit')
    op.drop_index(op.f('ix_audit_case_counters_tenant_id'), table_name='audit_case_counters', schema='audit')
    op.drop_table('audit_case_counters', schema='audit')
    # ### end Alembic commands ###
