"""drop audit_exceptions.case_id

Revision ID: eb177da98ba0
Revises: d7fb9f0ec989
Create Date: 2026-10-08 12:07:33.246663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb177da98ba0'
down_revision: Union[str, Sequence[str], None] = 'd7fb9f0ec989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_exceptions_case_id'), table_name='audit_exceptions', schema='audit')
    op.drop_column('audit_exceptions', 'case_id', schema='audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_exceptions', sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=True), schema='audit')
    op.create_index(op.f('ix_audit_exceptions_case_id'), 'audit_exceptions', ['case_id'], unique=False, schema='audit')
    # ### end Alembic commands ###
